spring.application.name=ms-pedidos
server.port=8081

# --- Base de datos (MySQL en Docker, ver docker-compose.yml en la raiz del repo) ---
spring.datasource.url=jdbc:mysql://localhost:3306/pedidos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=pedidos_user
spring.datasource.password=pedidos_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Validacion de JWT contra Azure AD (IDaaS) ---
azure.ad.issuer-uri=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/v2.0
azure.ad.audience=9078dcc3-9503-4237-a463-d5a4a96cb61f
